# Generated by Django 3.2 on 2021-06-22 03:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20210427_1227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('created',)},
        ),
        migrations.RemoveField(
            model_name='product',
            name='shu',
        ),
        migrations.AddField(
            model_name='product',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 3, 23, 16, 818171)),
        ),
        migrations.AddField(
            model_name='product',
            name='material_podoshvy',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='material_stelki',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='region',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 3, 23, 16, 818202)),
        ),
    ]
