# Generated by Django 3.2 on 2021-06-22 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_auto_20210622_0324'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='kabluk_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='material_podkladki',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='material_top',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='top_height',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
