# Generated by Django 3.2 on 2021-06-22 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_product_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
