# Generated by Django 3.2 on 2021-06-22 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='articul',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
