# Generated by Django 3.2 on 2021-06-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_product_articul'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('articul',)},
        ),
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('Женская', 'Female'), ('Мужская', 'Male')], default='Женская', max_length=50),
        ),
    ]
