# Generated by Django 3.2 on 2021-06-29 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_auto_20210622_1541'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('-name',), 'verbose_name_plural': 'categoriess'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('updated',)},
        ),
    ]
